services:

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - redis
