### Zip Code
GET http://127.0.0.1:8080/get_address/13330250 HTTP/1.1
Content-Type: application/json

### Weather
POST http://127.0.0.1:8080/get_weather HTTP/1.1
Content-Type: application/json
Content-Type: application/json

{
  "cep": "13330-250",
  "logradouro": "Rua Hércules Mazzoni",
  "complemento": "",
  "bairro": "Centro",
  "localidade": "Indaiatuba",
  "uf": "SP",
  "ibge": "3520509",
  "gia": "3530",
  "ddd": "19",
  "siafi": "6511"
}